        <html><head></head><body>
        <h1>Report for alsa-lib on toolchain
            <a href="index.html">vanilla</a>
        </h1>
        <p>Return code: 1</p>
        <p>Time to run: 00:00:15</p>
        <p>Log output:</p>
        <code><pre><docker run --rm -v /tuscan_data --volumes-from tuscan_data -v /sources --volumes-from sources -v /var/cache/pacman/pkg --volumes-from pkg_cache_vanilla -v logs:/logs make_package_container --sources-directory /sources --shared-directory /tuscan_data alsa-lib
:: Synchronizing package databases...
downloading repo.db...
downloading core.db...
downloading extra.db...
downloading community.db...
Found 2117 packages in cache
Found permanent source directory in /sources/alsa-lib
Traceback (most recent call last):
  File "/build/make_package.py", line 215, in <module>
    main()
  File "/build/make_package.py", line 212, in main
    result = copy_and_build(args)
  File "/build/make_package.py", line 118, in copy_and_build
    copytree(permanent_source_dir, build_dir)
  File "/usr/lib/python3.5/shutil.py", line 353, in copytree
    raise Error(errors)
shutil.Error: [('/sources/alsa-lib/src/alsa-lib-1.0.29/include/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa', '/tmp/alsa-lib/src/alsa-lib-1.0.29/include/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa', "[Errno 40] Too many levels of symbolic links: '/sources/alsa-lib/src/alsa-lib-1.0.29/include/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa'")]></pre></code>
        </body></html>
