        <html><head></head><body>
        <h1>Report for gcin on toolchain
            <a href="index.html">vanilla</a>
        </h1>
        <p>Return code: 1</p>
        <p>Time to run: 00:00:08</p>
        <p>Log output:</p>
        <code><pre><docker run --rm -v /tuscan_data --volumes-from tuscan_data -v /sources --volumes-from sources -v /var/cache/pacman/pkg --volumes-from pkg_cache_vanilla -v logs:/logs make_package_container --sources-directory /sources --shared-directory /tuscan_data gcin
:: Synchronizing package databases...
downloading repo.db...
downloading core.db...
downloading extra.db...
downloading community.db...
Found 3244 packages in cache
Found permanent source directory in /sources/gcin
Traceback (most recent call last):
  File "/build/make_package.py", line 215, in <module>
    main()
  File "/build/make_package.py", line 212, in main
    result = copy_and_build(args)
  File "/build/make_package.py", line 118, in copy_and_build
    copytree(permanent_source_dir, build_dir)
  File "/usr/lib/python3.5/shutil.py", line 353, in copytree
    raise Error(errors)
shutil.Error: [('/sources/gcin/src/gcin-2.8.4/gcin.test', '/tmp/gcin/src/gcin-2.8.4/gcin.test', "[Errno 2] No such file or directory: '/sources/gcin/src/gcin-2.8.4/gcin.test'"), ('/sources/gcin/src/gcin-2.8.4/libgcin-im-client.so.1', '/tmp/gcin/src/gcin-2.8.4/libgcin-im-client.so.1', "[Errno 2] No such file or directory: '/sources/gcin/src/gcin-2.8.4/libgcin-im-client.so.1'"), ('/sources/gcin/src/gcin-2.8.4/ts-edit-en', '/tmp/gcin/src/gcin-2.8.4/ts-edit-en', "[Errno 2] No such file or directory: '/sources/gcin/src/gcin-2.8.4/ts-edit-en'"), ('/sources/gcin/src/gcin-2.8.4/ts-contribute-en', '/tmp/gcin/src/gcin-2.8.4/ts-contribute-en', "[Errno 2] No such file or directory: '/sources/gcin/src/gcin-2.8.4/ts-contribute-en'")]></pre></code>
        </body></html>
