        <html><head></head><body>
        <h1>Report for networkmanager on toolchain
            <a href="index.html">vanilla</a>
        </h1>
        <p>Return code: 1</p>
        <p>Time to run: 00:00:26</p>
        <p>Log output:</p>
        <code><pre><docker run --rm -v /tuscan_data --volumes-from tuscan_data -v /sources --volumes-from sources -v /var/cache/pacman/pkg --volumes-from pkg_cache_vanilla -v logs:/logs make_package_container --sources-directory /sources --shared-directory /tuscan_data networkmanager
:: Synchronizing package databases...
downloading repo.db...
downloading core.db...
downloading extra.db...
downloading community.db...
Found 3038 packages in cache
Found permanent source directory in /sources/networkmanager
Traceback (most recent call last):
  File "/build/make_package.py", line 215, in <module>
    main()
  File "/build/make_package.py", line 212, in main
    result = copy_and_build(args)
  File "/build/make_package.py", line 118, in copy_and_build
    copytree(permanent_source_dir, build_dir)
  File "/usr/lib/python3.5/shutil.py", line 353, in copytree
    raise Error(errors)
shutil.Error: [('/sources/networkmanager/src/path/python', '/tmp/networkmanager/src/path/python', "[Errno 2] No such file or directory: '/sources/networkmanager/src/path/python'"), ('/sources/networkmanager/src/NetworkManager/m4/gtk-doc.m4', '/tmp/networkmanager/src/NetworkManager/m4/gtk-doc.m4', "[Errno 2] No such file or directory: '/sources/networkmanager/src/NetworkManager/m4/gtk-doc.m4'"), ('/sources/networkmanager/src/NetworkManager/gtk-doc.make', '/tmp/networkmanager/src/NetworkManager/gtk-doc.make', "[Errno 2] No such file or directory: '/sources/networkmanager/src/NetworkManager/gtk-doc.make'")]></pre></code>
        </body></html>
