        <html><head></head><body>
        <h1>Report for task on toolchain
            <a href="index.html">vanilla</a>
        </h1>
        <p>Return code: 1</p>
        <p>Time to run: 00:00:14</p>
        <p>Log output:</p>
        <code><pre><docker run --rm -v /tuscan_data --volumes-from tuscan_data -v /sources --volumes-from sources -v /var/cache/pacman/pkg --volumes-from pkg_cache_vanilla -v logs:/logs make_package_container --sources-directory /sources --shared-directory /tuscan_data task
:: Synchronizing package databases...
downloading repo.db...
downloading core.db...
downloading extra.db...
downloading community.db...
Found 1804 packages in cache
Found permanent source directory in /sources/task
Traceback (most recent call last):
  File "/build/make_package.py", line 215, in <module>
    main()
  File "/build/make_package.py", line 212, in main
    result = copy_and_build(args)
  File "/build/make_package.py", line 118, in copy_and_build
    copytree(permanent_source_dir, build_dir)
  File "/usr/lib/python3.5/shutil.py", line 353, in copytree
    raise Error(errors)
shutil.Error: [('/sources/task/src/task-2.5.0/src/cal', '/tmp/task/src/task-2.5.0/src/cal', "[Errno 2] No such file or directory: '/sources/task/src/task-2.5.0/src/cal'"), ('/sources/task/src/task-2.5.0/src/tw', '/tmp/task/src/task-2.5.0/src/tw', "[Errno 2] No such file or directory: '/sources/task/src/task-2.5.0/src/tw'"), ('/sources/task/src/task-2.5.0/src/calendar', '/tmp/task/src/task-2.5.0/src/calendar', "[Errno 2] No such file or directory: '/sources/task/src/task-2.5.0/src/calendar'")]></pre></code>
        </body></html>
