        <html><head></head><body>
        <h1>Report for pypy3 on toolchain
            <a href="index.html">android</a>
        </h1>
        <p>Return code: 5</p>
        <p>Time to run: 00:01:27</p>
        <p>Log output:</p>
        <code><pre><docker run --rm -v /tuscan_data --volumes-from tuscan_data -v /sources --volumes-from sources -v /var/cache/pacman/pkg --volumes-from pkg_cache_android -v logs:/logs make_package_container --sources-directory /sources --shared-directory /tuscan_data pypy3
:: Synchronizing package databases...
downloading repo.db...
downloading core.db...
downloading extra.db...
downloading community.db...
Found 2380 packages in cache
===> sudo -u tuscan makepkg --nobuild --syncdeps --skipinteg --skippgpcheck --skipchecksums --noconfirm --nocolor --log --noprogressbar --nocheck
==> Making package: pypy3 2.4.0-3 (Sat Nov 14 00:22:39 UTC 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...
warning: dependency cycle detected:
warning: harfbuzz will be installed before its freetype2 dependency

Packages (23) fontconfig-2.11.1-2  freetype2-2.6.1-1  graphite-1:1.3.3-1  harfbuzz-1.0.6-2  kbproto-1.0.7-1  libpng-1.6.18-1  libx11-1.6.3-1  libxau-1.0.8-2  libxcb-1.11.1-1  libxdmcp-1.1.2-1  libxext-1.3.3-1  libxft-2.3.2-1  libxrender-0.9.9-1  libxss-1.2.2-2  renderproto-0.11.1-3  scrnsaverproto-1.2.2-2  tcl-8.6.4-1  xcb-proto-1.11-2  xextproto-7.3.0-1  xproto-7.0.28-1  python2-2.7.10-2  sqlite-3.9.2-1  tk-8.6.4-1

Total Installed Size:  111.56 MiB

:: Proceed with installation? [Y/n] 
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
installing sqlite...
installing python2...
Optional dependencies for python2
    tk: for IDLE [pending]
    python2-setuptools
    python2-pip
installing tcl...
installing xcb-proto...
installing xproto...
installing libxdmcp...
installing libxau...
installing libxcb...
installing kbproto...
installing libx11...
installing xextproto...
installing libxext...
installing scrnsaverproto...
installing libxss...
installing libpng...
installing graphite...
installing harfbuzz...
Optional dependencies for harfbuzz
    cairo: hb-view program
installing freetype2...
installing fontconfig...

  Fontconfig configuration is done via /etc/fonts/conf.avail and conf.d.
  Read /etc/fonts/conf.d/README for more information.

  Configuration via /etc/fonts/local.conf is still possible,
  but is no longer recommended for options available in conf.avail.

  Main systemwide configuration should be done by symlinks
  (especially for autohinting, sub-pixel and lcdfilter):

  cd /etc/fonts/conf.d
  ln -s ../conf.avail/XX-foo.conf

  Check also https://wiki.archlinux.org/index.php/Font_Configuration
  and https://wiki.archlinux.org/index.php/Fonts.

updating font cache... done.
installing renderproto...
installing libxrender...
installing libxft...
installing tk...
==> Retrieving sources...
  -> Downloading pypy3-2.4.0-src.tar.bz2...
  -> Found trackgcroot-new-ops.patch
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Extracting pypy3-2.4.0-src.tar.bz2 with bsdtar
==> Starting prepare()...
patching file rpython/translator/c/gcc/trackgcroot.py
==> Sources are ready.
Copied source directory to /sources/pypy3
===> sudo -u tuscan PATH=/tmp/toolchain/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin CC=arm-linux-androideabi-gcc CXX=arm-linux-androideabi-g++ SYSROOT=/build/android-ndk-r10e/platforms/android-21/arch-arm makepkg --noextract --syncdeps --skipinteg --skippgpcheck --skipchecksums --noconfirm --nocolor --log --noprogressbar --nocheck
==> Making package: pypy3 2.4.0-3 (Sat Nov 14 00:23:24 UTC 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
[translation:info] 2.7.5 (default, Jul 13 2014, 15:59:34)
[translation:info] [GCC 4.6.x-google 20120106 (prerelease)]
[platform:msg] Set platform with 'host' cc=None, using cc='arm-linux-androideabi-gcc'
[translation:info] Translating target as defined by targetpypystandalone
[platform:execute] arm-linux-androideabi-gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-pypy3-release-2.4.x-0/gcctest.c -o /tmp/usession-pypy3-release-2.4.x-0/gcctest.o
[platform:execute] arm-linux-androideabi-gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-pypy3-release-2.4.x-0/gcctest.c -o /tmp/usession-pypy3-release-2.4.x-0/gcctest.o
[platform:execute] arm-linux-androideabi-gcc /tmp/usession-pypy3-release-2.4.x-0/gcctest.o -pthread -lrt -o /tmp/usession-pypy3-release-2.4.x-0/gcctest
[platform:Error] /tmp/toolchain/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lrt
[platform:Error] collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "../../rpython/bin/rpython", line 20, in <module>
    main()
  File "/tmp/pypy3/src/pypy3-2.4.0-src/rpython/translator/goal/translate.py", line 217, in main
    targetspec_dic, translateconfig, config, args = parse_options_and_load_target()
  File "/tmp/pypy3/src/pypy3-2.4.0-src/rpython/translator/goal/translate.py", line 156, in parse_options_and_load_target
    targetspec_dic = load_target(targetspec)
  File "/tmp/pypy3/src/pypy3-2.4.0-src/rpython/translator/goal/translate.py", line 98, in load_target
    mod = __import__(specname)
  File "targetpypystandalone.py", line 11, in <module>
    from rpython.rlib import rlocale
  File "/tmp/pypy3/src/pypy3-2.4.0-src/rpython/rlib/rlocale.py", line 7, in <module>
    from rpython.rtyper.lltypesystem import rffi, lltype
  File "/tmp/pypy3/src/pypy3-2.4.0-src/rpython/rtyper/lltypesystem/rffi.py", line 514, in <module>
    NUMBER_TYPES = setup()
  File "/tmp/pypy3/src/pypy3-2.4.0-src/rpython/rtyper/lltypesystem/rffi.py", line 503, in setup
    names = populate_inttypes()
  File "/tmp/pypy3/src/pypy3-2.4.0-src/rpython/rtyper/lltypesystem/rffi.py", line 497, in populate_inttypes
    platform.populate_inttypes(populatelist)
  File "/tmp/pypy3/src/pypy3-2.4.0-src/rpython/rtyper/tool/rfficache.py", line 83, in populate_inttypes
    sizes = sizeof_c_types(names_c, **kwds)
  File "/tmp/pypy3/src/pypy3-2.4.0-src/rpython/rtyper/tool/rfficache.py", line 45, in sizeof_c_types
    answer = ask_gcc(question, **kwds)
  File "/tmp/pypy3/src/pypy3-2.4.0-src/rpython/rtyper/tool/rfficache.py", line 35, in ask_gcc
    return build_executable_cache([c_file], eci, ignore_errors=ignore_errors)
  File "/tmp/pypy3/src/pypy3-2.4.0-src/rpython/tool/gcc_cache.py", line 28, in build_executable_cache
    result = platform.execute(platform.compile(c_files, eci))
  File "/tmp/pypy3/src/pypy3-2.4.0-src/rpython/translator/platform/__init__.py", line 54, in compile
    return self._finish_linking(ofiles, eci, outputfilename, standalone)
  File "/tmp/pypy3/src/pypy3-2.4.0-src/rpython/translator/platform/__init__.py", line 241, in _finish_linking
    return self._link(cc_link, ofiles, largs, standalone, exe_name)
  File "/tmp/pypy3/src/pypy3-2.4.0-src/rpython/translator/platform/posix.py", line 74, in _link
    cwd=str(exe_name.dirpath()))
  File "/tmp/pypy3/src/pypy3-2.4.0-src/rpython/translator/platform/__init__.py", line 139, in _execute_c_compiler
    self._handle_error(returncode, stdout, stderr, outname)
  File "/tmp/pypy3/src/pypy3-2.4.0-src/rpython/translator/platform/__init__.py", line 151, in _handle_error
    raise CompilationError(stdout, stderr)
rpython.translator.platform.CompilationError: CompilationError(err="""
	/tmp/toolchain/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lrt
	collect2: error: ld returned 1 exit status
	""")
==> ERROR: A failure occurred in build().
    Aborting...
===> Printing config.logs
===> Finished printing config.logs></pre></code>
        </body></html>
