        <html><head></head><body>
        <h1>Report for sage-data-polytopes_db on toolchain
            <a href="index.html">android</a>
        </h1>
        <p>Return code: 3</p>
        <p>Time to run: 00:00:21</p>
        <p>Log output:</p>
        <code><pre><docker run --rm -v /tuscan_data --volumes-from tuscan_data -v /sources --volumes-from sources -v /var/cache/pacman/pkg --volumes-from pkg_cache_android -v logs:/logs make_package_container --sources-directory /sources --shared-directory /tuscan_data sage-data-polytopes_db
:: Synchronizing package databases...
downloading repo.db...
downloading core.db...
downloading extra.db...
downloading community.db...
Found 869 packages in cache
===> sudo -u tuscan makepkg --nobuild --syncdeps --skipinteg --skippgpcheck --skipchecksums --noconfirm --nocolor --log --noprogressbar --nocheck
==> Making package: sage-data-polytopes_db 20120220-2 (Fri Nov 13 23:17:23 UTC 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading polytopes_db-20120220.tar.bz2...
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading polytopes_db-20120220.tar.bz2
    Aborting...
Unable to get sources for package 'sage-data-polytopes_db'
===> Printing config.logs
===> Finished printing config.logs></pre></code>
        </body></html>
